---
- name: Deploy Kubernetes Deployment and Service
  hosts: localhost
  tasks : 
  - name: Performing Deployment of testapp
    command: "kubectl apply -f kubewebapp.yaml --kubeconfig=/home/labsuser/.kube/config --context=kubernetes-admin@kubernetes"
    
