---
- name: Deploy Kubernetes Deployment and Service
  hosts: localhost
  tasks : 
  - name: Performing Deployment of testapp
    command: "kubectl delete -f kubewebapp.yaml --kubeconfig=kubeconfig --context=kubernetes-admin@kubernetes"
    ignore_errors: true
  - name: Performing Deployment of testapp
    command: "kubectl apply -f kubewebapp.yaml --kubeconfig=kubeconfig --context=kubernetes-admin@kubernetes"
    
