---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orbitbankapp
  name: orbitbankapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitbankapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orbitbankapp
    spec:
      containers:
      - image: rakshithdevops.azurecr.io/bankapp
        name: orbitbankapp
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orbitbankapp
  name: orbitbankapp
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
    nodePort: 32000
  selector:
    app: orbitbankapp
  type: LoadBalancer
status:
  loadBalancer: {}

