---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testapp
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testapp
    spec:
      containers:
      - image: docker.io/kotianrakshith/testapp
        name: testapp
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testapp
  name: testapp
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
    nodePort: 32000
  selector:
    app: testapp
  type: NodePort
status:
  loadBalancer: {}

